# 광고그룹 분석
- 학습목표
    1. groupby함수 사용실습
    2. 키워드 분석과정에서 진행한 코딩 복습

In [1]:
import pandas as pd
from pandas import DataFrame
from pandas import Series

In [2]:
import matplotlib.pyplot as plt

In [3]:
#matplotlib 한글 폰트 출력코드
#출처 : 데이터 공방 (http:// kiddwannabe.blog.me)

import matplotlib
from matplotlib import font_manager, rc
import platform

try :
    #맥인 경우
    rc('font', family = 'AppleGothic')

except :
    pass
matplotlib.rcParams['axes.unicode_minus'] = False

In [4]:
df = pd.read_excel('/Users/jeonghyeonjeong/Desktop/실습데이터_네이버보고서.xls', skiprows=[0])

앞의 '검색광고 데이터 분석3_데이터 분석'에서는
## as-is : 키워드 기준 분석
을 해 왔다. 
- 키워드의 노출수/ 클릭수/ 총 비용...

지금 광고그룹 분석에서는
## 1. to-be : 광고그룹 기준 분석
을 할 것이다. 
- 데이터의 구성을 광고그룹 기준으로 변경해야한다. 
- 광고그룹의 노출수/ 클릭수 / 총 비용... 등을 groupby함수를 사용하여 분석한다. 
         groupby 함수 : 전달된 열을 기준으로 전체 데이터를 분류하는 함수

In [5]:
grouped = df.groupby('광고그룹') #'광고그룹'이라는 column의 정보를 grouped 변수에 할당

In [6]:
#grouped변수 출력시 객체 정보만 출력됨
grouped

In [7]:
#그래서 이 변수 내의 데이터를 살펴보기 위해서는 집계함수를 사용해야 함
grouped.count() #count함수 : 데이터의 갯수를 집계

                         키워드  노출수  클릭수  클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)
광고그룹
#000_마케팅 전체_main          48   48   48      48               48            48
001.BASIC DESIGN           9    9    9       9                9             9
001.데이터분석/ 통계             10   10   10      10               10            10
002.R                      9    9    9       9                9             9
002.UX/UI                  5    5    5       5                5             5
...                      ...  ...  ...     ...              ...           ...
포토샵 유치원_일러스트레이터 유치원       13   13   13      13               13            13
프로그래밍 유치원                  8    8    8       8                8             8
프로그래밍 전체                  12   12   12      12               12            12
프로그래밍 전체_파워컨텐츠_블록체인(삭제)    3    3    3       3                3             3
프론트엔드 개발 스쿨 12기_기존 키워드     1    1    1       1                1             1

[186 rows x 6 columns]

In [8]:
grouped.mean() #각 column에 대한 평균값

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
광고그룹,,,,,
#000_마케팅 전체_main,14780.145833,8.400000,0.183898,625.086295,7243.958333
001.BASIC DESIGN,5738.555556,6.800000,0.232924,298.693822,2427.333333
001.데이터분석/ 통계,3715.000000,20.280000,0.890571,1021.473357,19575.600000
002.R,13413.777778,8.533333,0.111199,360.038462,4796.000000
002.UX/UI,3090.800000,4.080000,0.089340,69.928571,550.000000
...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,72092.692308,16.707692,0.050832,648.327517,15781.615385
프로그래밍 유치원,5921.625000,7.800000,0.224738,2032.326389,23617.000000
프로그래밍 전체,90375.000000,9.200000,0.024037,123.881559,1626.166667
프로그래밍 전체_파워컨텐츠_블록체인(삭제),65353.333333,2344.400000,3.643359,192.773927,431159.666667
프론트엔드 개발 스쿨 12기_기존 키워드,2015.000000,2.400000,0.119107,64.166667,154.000000

In [9]:
grouped.median() #중앙값

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
광고그룹,,,,,
#000_마케팅 전체_main,2765.0,3.6,0.055948,765.972222,2458.5
001.BASIC DESIGN,5524.0,2.4,0.038716,357.500000,1023.0
001.데이터분석/ 통계,1813.0,13.8,0.573846,1096.795393,13464.0
002.R,5184.0,3.6,0.028016,119.166667,1287.0
002.UX/UI,2649.0,1.2,0.090600,73.333333,88.0
...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,5763.0,3.6,0.023327,852.500000,2706.0
프로그래밍 유치원,3748.0,3.0,0.121833,1763.819444,8002.5
프로그래밍 전체,3455.5,1.2,0.009331,130.497685,225.5
프로그래밍 전체_파워컨텐츠_블록체인(삭제),64981.0,2798.4,3.517502,239.805985,334961.0
프론트엔드 개발 스쿨 12기_기존 키워드,2015.0,2.4,0.119107,64.166667,154.0

In [10]:
grouped.std() # 그룹데이터의 표준편차

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
광고그룹,,,,,
#000_마케팅 전체_main,43495.109992,17.731616,0.314900,472.866258,15854.712974
001.BASIC DESIGN,4182.624120,9.138928,0.471768,176.145753,3220.042158
001.데이터분석/ 통계,4109.836709,18.316768,0.817334,269.588218,19127.395160
002.R,19333.628900,14.714619,0.165559,371.704042,10077.594033
002.UX/UI,1996.647866,7.179972,0.105666,69.105148,1005.282050
...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,188247.583461,35.267418,0.060497,470.848706,37543.642006
프로그래밍 유치원,6642.341496,9.769925,0.251239,1649.704939,37088.923190
프로그래밍 전체,200385.152836,17.263730,0.034516,119.977104,2801.701328
프로그래밍 전체_파워컨텐츠_블록체인(삭제),25831.512622,820.884499,0.610018,121.019420,335034.366480
프론트엔드 개발 스쿨 12기_기존 키워드,NaN,NaN,NaN,NaN,NaN

In [11]:
grouped.var() #각 데이터의 분산

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
광고그룹,,,,,
#000_마케팅 전체_main,1.891825e+09,314.410213,0.099162,2.236025e+05,2.513719e+08
001.BASIC DESIGN,1.749434e+07,83.520000,0.222565,3.102733e+04,1.036867e+07
001.데이터분석/ 통계,1.689076e+07,335.504000,0.668035,7.267781e+04,3.658572e+08
002.R,3.737892e+08,216.520000,0.027410,1.381639e+05,1.015579e+08
002.UX/UI,3.986603e+06,51.552000,0.011165,4.775522e+03,1.010592e+06
...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,3.543715e+10,1243.790769,0.003660,2.216985e+05,1.409525e+09
프로그래밍 유치원,4.412070e+07,95.451429,0.063121,2.721526e+06,1.375588e+09
프로그래밍 전체,4.015421e+10,298.036364,0.001191,1.439451e+04,7.849530e+06
프로그래밍 전체_파워컨텐츠_블록체인(삭제),6.672670e+08,673851.360000,0.372122,1.464570e+04,1.122480e+11
프론트엔드 개발 스쿨 12기_기존 키워드,NaN,NaN,NaN,NaN,NaN

## 2. 광고그룹 기준 데이터 전처리

In [13]:
#그룹데이터의 합계 - 노출수, 클릭수, 총비용 총 합계를 구해보자. 
grouped.sum() #근데 아래에 나온 결과는 '키워드'에 대한 노출수, 클릭수, 총비용 의 총 합이다. 
#그래서 '광고그룹'에 대한 노출수, 클릭수, 총비용 총 합으로 바꿔야 할 필요가 있다.

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
광고그룹,,,,,
#000_마케팅 전체_main,709447,403.2,8.827081,30004.142165,347710
001.BASIC DESIGN,51647,61.2,2.096316,2688.244398,21846
001.데이터분석/ 통계,37150,202.8,8.905710,10214.733573,195756
002.R,120724,76.8,1.000794,3240.346154,43164
002.UX/UI,15454,20.4,0.446702,349.642857,2750
...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,937205,217.2,0.660812,8428.257716,205161
프로그래밍 유치원,47373,62.4,1.797903,16258.611111,188936
프로그래밍 전체,1084500,110.4,0.288445,1486.578704,19514
프로그래밍 전체_파워컨텐츠_블록체인(삭제),196060,7033.2,10.930078,578.321782,1293479
프론트엔드 개발 스쿨 12기_기존 키워드,2015,2.4,0.119107,64.166667,154

In [14]:
#그러기 위한 전처리 필요
df_group = grouped.sum()

#### 1. 클릭률(클릭수/노출수) 전처리 : 데이터프레임의 열 단위 수치연산

In [16]:
df_group['클릭률(%)'] =  df_group['클릭수'] / df_group['노출수']

#### 2. 평균 클릭비용(cpc) 전처리 : 총비용 / 클릭수

In [19]:
df_group['평균클릭비용(VAT포함,원)'] = df_group['총비용(VAT포함,원)'] / df_group['클릭수']

In [23]:
#그런데 나누는 수가 되는 df_group['클릭수']가 0인 것이 있어, df_group['평균클릭비용(VAT포함,원)']의 결과가 nan이 되는 게 있다. 이런거 전처리 필요

                               노출수  클릭수  클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)
광고그룹
Hyperledger Fabric 프로젝트 CAMP  1990  0.0     0.0              NaN             0
fin_camp_business_4           2136  0.0     0.0              NaN             0
fin_camp_rfs_9                1928  0.0     0.0              NaN             0
다함께 DDD 프로젝트                  3689  0.0     0.0              NaN             0
올인원 패키지 : 디지털 마케팅_인스타광고       1377  0.0     0.0              NaN             0

In [27]:
#이럴때는 'nan에 전달된 값으로 결측값을 대체하는 함수(fillna(대체하고 싶은 값))'를 이용하여 nan부분을 채워준다. 
df_group['평균클릭비용(VAT포함,원)'] = df_group['평균클릭비용(VAT포함,원)'].fillna(0)
df_group[df_group['클릭수']==0] #아래와 같이 결측값이 0으로 다 채워졌음을 알 수 있다.

                               노출수  클릭수  클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)
광고그룹
Hyperledger Fabric 프로젝트 CAMP  1990  0.0     0.0              0.0             0
fin_camp_business_4           2136  0.0     0.0              0.0             0
fin_camp_rfs_9                1928  0.0     0.0              0.0             0
다함께 DDD 프로젝트                  3689  0.0     0.0              0.0             0
올인원 패키지 : 디지털 마케팅_인스타광고       1377  0.0     0.0              0.0             0

#### 3. '원'단위인 것은 소수점이 없어야 하니까 반올림처리하는 전처리

In [28]:
#반올림처리 함수 (round), 소수점 제거 함수(astype(int))
df_group['평균클릭비용(VAT포함,원)'] = round(df_group['평균클릭비용(VAT포함,원)'], 0) #반올림 처리
df_group['평균클릭비용(VAT포함,원)'] = df_group['평균클릭비용(VAT포함,원)'].astype(int) #정수형으로 바꿈
df_group.head()

                     노출수    클릭수    클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)
광고그룹
#000_마케팅 전체_main  709447  403.2  0.000568              862        347710
001.BASIC DESIGN   51647   61.2  0.001185              357         21846
001.데이터분석/ 통계      37150  202.8  0.005459              965        195756
002.R             120724   76.8  0.000636              562         43164
002.UX/UI          15454   20.4  0.001320              135          2750